---
- name: Nginx Installation and Start & Enable
  hosts: all
  gather_facts: yes
  tasks:
    - name: Install epel-release
      when: ansible_distribution == "CentOS"
      yum: # module
        name: epel-release
        state: latest

    - name: Install nginx on Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt: #module
        name: nginx
        state: latest

    - name: Install Nginx on CentOS
      yum: # module
        name: nginx
        state: latest

    - name: Start and Enable Nginx
      systemd:
        name: nginx
        state: stopped
        enabled: yes

    




  

             