--- # Start of YML file
- name: Update Packages , Install Packages, Create and insert lines to a file
  hosts: 10.108.0.6
  tasks: 
    - name: Update all "yum" packages
      yum: #module
        name: '*'
        state: latest

    - name: Install Packages
      yum: #module
        name:
          - vim
          - tree
          - wget
        state: latest

    - name: Create an empty file
      file: #module
        path: /tmp/file1_ansible
        state: touch

    - name: Insert lines to a file
      blockinfile:
        path: /tmp/file1_ansible
        block: |
          this is line one
          this is line two
          this is line three

    - name: Install nginx package
      yum: #module
        name: nginx
        state: present     
           
           

        
        
