--- # Start of YML file
- name: Name of the Play
  hosts: localhost
  tasks: 
    - name: 
      yum: #module
        name: '*'
        state: latest

    - name: Name of Task2
      yum: #module
        name:
          - vim
          - tree
          - wget
          - curl
        state: latest

    - name: Name of task3
      file: #module
        path: /tmp/file1_ansible
        state: touch
    - name: Name of task4
      blockinfile:
        path: /tmp/file1_ansible
        block: |
          this is line one
          this is line two
           
           

        
        
